# Nombre de la aplicación
spring.application.name=the-theatre-backend

# --- Conexión a Base de Datos ---
spring.datasource.url=jdbc:postgresql://localhost:5432/theatredb
spring.datasource.username=admin_theatre
spring.datasource.password=password123
spring.datasource.driver-class-name=org.postgresql.Driver

# --- Configuración de JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- CONFIGURACIÓN JWT (NUEVO) ---
application.security.jwt.secret-key=bWljbGF2ZXN1cGVyc2VjcmV0YXlsYXJnYXBhcmFxdWVqd3RmdW5jaW9uZTIwMjQ=
# Tiempo de expiración: 86400000 ms = 24 horas
application.security.jwt.expiration=86400000